name: my_flutter_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  dio:
  freezed_annotation: ^0.14.3

  logger:

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^0.14.0
  json_serializable: ^5.0.1


flutter:
  uses-material-design: true
  generate: true
